######################################################
## Landstar App Deployment Guide - STAGING (v1.1.1) ##
######################################################
## This yaml is used to apply STAGING environmental settings to override the SAME items found in the deployment_guide.yml (Prod) doc.
## ONLY the items already outlined below are currently supported for environmental override.
##
## *NOTES*
##   Help comments in this template are prepended with "##"
##   Commented yaml portions are prepended with a single "#"
##   Always ensure that any uncommented items retain proper yaml indentation.
##     Sub items should always be indented 2 SPACES, and tabs are not allowed.
##
## *Recent changes*
##   - Added host alias env overrides


##################
##  Configmaps  ##
##################
## NOTE - the entire configmap from the deployment_guide.yml must be defined here, AND
##        values for 'name'/'keyname' MUST match for overrides to work properly.
## Uncomment lines below to override/create STAGING specific configmaps
## Duplicate lines below 'configmaps' (name, data, & keyname) for multiple configmaps
## Duplicate the 'keyname' line (as needed) for multiple key/value pairs in the same configmap
#configmaps: 
#  - name: name 
#    data:
#      keyname: value 


##########################
## NGINX EXT Configmaps ##
##########################
## Nginx configs for EXTERNAL traffic. Usually associated with Azure Front Door configuration.
## Uncomment lines below to override external nginx entry in STAGING env.
## NOTE - single quotes can NOT be used in your nginx config
## 'key' -- Replace 'new_key' with the same name used in 'NGINX EXT Configmaps' section of deployment_guide.yml.
## Then CAREFULLY edit the lines *BELOW* 'value |'. MUST maintain proper indentation.
nginx_ext_configmaps:             ## Replace value for 'key' with desired key name (normally workload name) & 'value' with a specific value
  - key: "identity.conf"           ## MUST have .conf file extension
    value: |
        server {
            large_client_header_buffers 4 128k;
            listen 8080;
            server_name  identitystg.landstaronline.com;            
            return 301 https://identitystg.landstaronline.com$request_uri;
            location /health {
            access_log off;
            error_log off;
            }
         }
         server {
            large_client_header_buffers 4 128k;
            listen 8080;
            server_name  identitystg.landstarblue.com;            
            return 301 https://identitystg.landstarblue.com$request_uri;
            location /health {
            access_log off;
            error_log off;
            }
         }
         server {
            server_name  identitystg.landstarblue.com;
            listen       8443 ssl http2;
            include server_blocks/common.cfg;
            large_client_header_buffers 4 128k;
            ssl_certificate      /certsblue/tls.crt;
            ssl_certificate_key  /certsblue/tls.key;
            ssl_session_cache    shared:SSL:1m;
            ssl_session_timeout  5m;
            ssl_protocols TLSv1.2; 
            ssl_prefer_server_ciphers on;
            ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
            ssl_ecdh_curve secp384r1;
            #ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            resolver 8.8.8.8 1.1.1.1 valid=300s;
            resolver_timeout 5s;            
            location / {
            add_header "Access-Control-Allow-Credentials" "true" always;
            add_header "Access-Control-Allow-Headers" "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range";
            add_header "Access-Control-Allow-Methods" "GET,POST,OPTIONS,PUT,DELETE,PATCH";
            if ($request_method = "OPTIONS") {
              add_header "Access-Control-Allow-Origin" "$http_origin" always;
              add_header "Access-Control-Allow-Credentials" "true" always;
              add_header "Access-Control-Allow-Headers" "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range";
              add_header "Access-Control-Allow-Methods" "GET,POST,OPTIONS,PUT,DELETE,PATCH";
              add_header "Access-Control-Max-Age" 1728000;
              add_header "Content-Type" "text/plain charset=UTF-8";
              add_header "Content-Length" 0;
              return 204;
            }
                proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        expires -1;
        proxy_pass https://identityserver.default:8443;
            }
            location /health {
            access_log off;
            error_log off;
            }
          }
         server {
            server_name  identitystg.landstaronline.com;
            listen       8443 ssl http2;
            include server_blocks/common.cfg; 
            large_client_header_buffers 4 128k;
            ssl_certificate      /certs/tls.crt;
            ssl_certificate_key  /certs/tls.key;
            ssl_session_cache    shared:SSL:1m;
            ssl_session_timeout  5m;
            ssl_protocols TLSv1.2; 
            ssl_prefer_server_ciphers on;
            ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
            ssl_ecdh_curve secp384r1;
            #ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            #ssl_stapling on; #ensure your cert is capable
            #ssl_stapling_verify on; #ensure your cert is capable
            resolver 8.8.8.8 1.1.1.1 valid=300s;
            resolver_timeout 5s;            
            location / {
          # add_header "Access-Control-Allow-Origin" "$http_origin" always;
            add_header "Access-Control-Allow-Credentials" "true" always;
            add_header "Access-Control-Allow-Headers" "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range";
            add_header "Access-Control-Allow-Methods" "GET,POST,OPTIONS,PUT,DELETE,PATCH";
            if ($request_method = "OPTIONS") {
              add_header "Access-Control-Allow-Origin" "$http_origin" always;
              add_header "Access-Control-Allow-Credentials" "true" always;
              add_header "Access-Control-Allow-Headers" "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range";
              add_header "Access-Control-Allow-Methods" "GET,POST,OPTIONS,PUT,DELETE,PATCH";
              add_header "Access-Control-Max-Age" 1728000;
              add_header "Content-Type" "text/plain charset=UTF-8";
              add_header "Content-Length" 0;
              return 204;
            }
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_no_cache 1;
            proxy_cache_bypass 1;
            expires -1;
            proxy_pass https://identityserver.default:8443;
            }
            location /health {
            access_log off;
            error_log off;
            }
        }    

##########################
## NGINX INT Configmaps ##
##########################
## Nginx configs for INTERNAL traffic. Usually associated with service exposure for other internal Landstar systems.
## Uncomment lines below to override internal nginx entry in STAGING env.
## NOTE - single quotes can NOT be used in your nginx config
## 'key' -- Replace 'new_key' with the same name used in 'NGINX INT Configmaps' section of deployment_guide.yml.
## Then CAREFULLY edit the lines *BELOW* 'value |'. MUST maintain proper indentation.
#nginx_int_configmaps:
#  - key: "new-key.conf"           ## Replace 'new-key' with the workload name the config is for. MUST have .conf file extension
#    ## CAREFULLY edit the lines *below* value to setup the entry for your workload. MUST maintain proper indentation.
#    value: |
#      server {
#        listen 8080;
#        server_name newstg-url.domain.com;
#        return 301 https://newstg-url.domain.com$request_uri;
#      }
#      server {
#        listen 8443 ssl;
#        server_name newstg-url.domain.com;
#        include server_blocks/common_ssl.cfg;
#        location /specific-endpoint {
#          include server_blocks/common.cfg;
#          proxy_pass http://workloadname.namespacename:8080;
#        }
#        location / {
#          include server_blocks/common.cfg;
#          proxy_pass http://workloadname.namespacename:8080;
#        }
#      }



###################
##  Deployments  ##
###################
## NOTE - values for 'name' MUST match what's in the deployment_guide.yml for overrides to work properly.
## STAGING specific local environment variables for app. Consider placing these in appsettings instead.
## Uncomment the 4 lines below. Duplicate the 2 lines below 'env_vars' for add. workload environment variables.
deployments:  
#  env_vars: 
#    - name: key_name
#      value: key_value

## Uncomment the line below to specify a different pod count for the AKS-STG cluster
  replicas: 2


################
##  Cronjobs  ##
################
## NOTE - values for 'name' MUST match what's in the deployment_guide.yml for overrides to work properly.
## STAGING specific local environment variables for app. Consider placing these in appsettings instead.
## Uncomment the 4 lines below. Duplicate the 2 lines below 'env_vars' for add. cronjob environment variables.
#cronjobs:  
#  env_vars: 
#    - name: key_name
#      value: key_value

## Uncomment the line below to specify a different cronjob status for the AKS-STG cluster
#  suspend: false