#################################################
## Landstar App Deployment Guide (v0.1.0)      ##
#################################################

#deployments:   
#  env_vars: 
      # Add additional Environmental Variable Name/Values as needed
    # - name: api_engine_name
    #   value: Identity Server (TEST)